version: "3"
services:
  app:
    build: .
    container_name: blog_app
    # command: /bin/sh entrypoint.sh
    entrypoint: /bin/sh
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    env_file:
      .env
    tty: true
    stdin_open: true
