version: "3"
services:
  app:
    build: .
    container_name: blog_app
    command: /bin/sh entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8080:4000"
    depends_on:
      - database
    links:
      - database
    tty: true
    stdin_open: true
  database:
    image: postgres:12
    container_name: blog_database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"